INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (1, 'Derecho');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (2, 'Relaciones Laborales y Recursos Humanos');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (3, 'Enfermería');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (4, 'Fisioterapia');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (5, 'Medicina');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (6, 'Psicología');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (7, 'Administración y Dirección de Empresas');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (8, 'Economía');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (9, 'Ingeniería Biomédica');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (10, 'Ingeniería Eléctrica y Electrónica');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (11, 'Ingeniería Informática');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (12, 'Ingeniería en Diseño Mecánico');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (13, 'Ingeniería Industrial');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (14, 'Ingeniería Mecánica');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (15, 'Ingeniería de Telecomunicaciones');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (16, 'Ingeniería Agroalimentaria y del Medio Rural');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (17, 'Historia y Patrimonio');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (18, 'Maestro en Educación Infantil');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (19, 'Haur Hezkuntzako Irakaslea');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (20, 'Maestro en Educación Primaria');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (21, 'Lehen Hezkuntzako Irakaslea');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (22, 'Sociología');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (23, 'Trabajo Social');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (24, 'Grado en Biotecnología');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (25, 'Grado en Ciencias');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (26, 'Grado en Ciencia de Datos');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (27, 'Innovación de Procesos y Productos Alimentarios');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (28, 'Doble Grado ADE y Derecho');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (29, 'Doble Grado ADE y Economía');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (30, 'Doble Grado ADE y Ciencia de Datos');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (31, 'Doble Grado en Maestro en Educación Infantil y Maestro en Educación Primaria');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (32, 'Doble Grado en Administración y Dirección de Empresas y en Derecho');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (33, 'Doble Grado en Ingeniería en Tecnologías de Telecomunicación e Ingeniería Biomédica');
INSERT INTO `carreras` (`idcarrera`, `nombre`) VALUES (34, 'Doble Grado en Ingeniería Agroalimentaria y del Medio Rural y en Innovación de Procesos y Productos Alimentarios');
