INSERT INTO `monitores` (idmonitor, nombre) VALUES (5205, 'T-Innova ');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (6042, 'Javier Escribano');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (6097, 'Peru Esteban');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (11930, 'Jessica Mateo');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (11945, 'Ana Isabel Herranz');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (17145, 'Miriam Insausti');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (18853, 'Luis Francisco Bautista');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (22685, 'Pedro Latasa');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (23166, 'Hodei Sarasa');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (23362, 'Gabriella De Rinaldis');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (23596, 'Iranzu Del Valle');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (24197, 'Juan Jose Armañanzas');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (24280, 'Ricardo Arizcuren');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (24389, 'Sedena ');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (25516, 'Irati Del Valle');
INSERT INTO `monitores` (idmonitor, nombre) VALUES (26238, 'Leyre Fernandez');
